### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [ChangWeiTan/FastWWSearch#2]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by ChangWeiTan** [comment]
Hi Sandy, this algorithm will not work for categorical data. You will need to encode your categorical data  into numbers for example red=1, green=2 etc. However, it is easy to extend to multivariate time series. May I know what do you need to use it for?

**Comment by Sandy4321** [comment]
Just want to learn warping

**Comment by ChangWeiTan** [comment]
Ok. Most of the work for Dynamic Time Warping are focused on univariate time series. However, this paper (https://link.springer.com/article/10.1007/s10618-016-0455-0) gives a good introduction to multivariate time series.
